services:
  - type: web
    name: rishabh-vendor-connect-frontend
    env: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://rishabh-vendor-connect.onrender.com/api
      - key: VITE_APP_NAME
        value: Rishabh Vendor Connect
      - key: VITE_APP_VERSION
        value: 1.0.0
