services:
  - type: web
    name: rishabh-vendor-connect-backend
    env: node
    plan: starter
    buildCommand: npm install --production
    startCommand: npm run start:production
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://rishabh_user:pU42wHRMU8YeHfiQA0Vr3wg1HsSVHQep@dpg-d3g0lcggjchc73826fvg-a.oregon-postgres.render.com/rishabh_vendor_connect
      - key: FRONTEND_URL
        value: https://rishabh-vendor-connect-frontend.onrender.com
      - key: STORAGE_TYPE
        value: local
      - key: UPLOAD_DIR
        value: /tmp/uploads
      - key: PDF_STORAGE_DIR
        value: /tmp/pdfs
    # Note: Persistent storage not available on free plan
    # Using ephemeral storage in /tmp for file uploads
    database:
      name: rishabh-vendor-connect-db
      plan: free
      databaseName: rishabh_vendor_connect
      user: rishabh_user

databases:
  - name: rishabh-vendor-connect-db
    plan: free
    databaseName: rishabh_vendor_connect
    user: rishabh_user
